all:
  vars:
    database: influx #influx or iotdb

    dataset: GPSMPU # Accel or GPSMPU
    current_time: true
    shared_dataset: true
    shared_connection: false

    iotdb_device_path: "root.gps.mpu.*"
    iotdb_version: 1.1.1
    
    
    # maybe most don't need to be variables
    influx_username: influx
    influx_password: influxpw
    influx_org: myorg
    influx_bucket: mybucket
    influx_token: mytoken
    influx_version: 2.7



    benchmark_client_version: v0.73
    benchmark_orchestrator_version: v0.73

    monitoring_interval: 2sec

    ansible_connection: ssh
    ansible_user: gsd
edgeservers:

cloudservers:
  hosts:
    cloud1:
      ansible_host: 192.168.112.75
      ansible_connection: ssh
      ansible_user: gsd
      limited_resources: false
      monitor: true
benchmark_clients:
  hosts:
    client1:
      stage: 1
      ansible_user: gsd
      ansible_host: 192.168.112.117
      monitor: true

      target: cloud1

      # data_file: data_1600_accel_watch.txt
      data_file: dataset_gps_mpu_left.csv
      num_workers: 64
      type: INSERT

      insert_volume: 240000 # total number of inserted points per worker
      batch_size: 200 # number of points per batch
      insert_rate: 5 # number of inserted batches per second per worker
    

    client2:
      stage: 1
      ansible_user: gsd
      ansible_host: 192.168.112.117
      monitor: true

      target: cloud1

      # data_file: data_1600_accel_watch.txt
      data_file: dataset_gps_mpu_left.csv
      num_workers: 64
      type: INSERT

      insert_volume: 240000 # total number of inserted points per worker
      batch_size: 200 # number of points per batch
      insert_rate: 5 # number of inserted batches per second per worker
      
    client3:
      stage: 1
      ansible_user: gsd
      ansible_host: 192.168.112.45
      monitor: true

      target: cloud1

    # data_file: data_1601_accel_watch.txt
      data_file: dataset_gps_mpu_left.csv
      num_workers: 48
      type: INSERT

      # num_loops: 2.0 # number of times dataset was inserted (only for standalone, do not use for scenario 1)

      insert_volume: 240000 # total number of inserted points per worker
      batch_size: 200 # number of points per batch
      insert_rate: 5 # number of inserted batches per second per worker
      

    client4:
      stage: 1
      ansible_user: gsd
      ansible_host: 192.168.112.45
      monitor: true

      target: cloud1

    # data_file: data_1601_accel_watch.txt
      data_file: dataset_gps_mpu_left.csv
      num_workers: 48
      type: INSERT

      # num_loops: 2.0 # number of times dataset was inserted (only for standalone, do not use for scenario 1)

      insert_volume: 240000 # total number of inserted points per worker
      batch_size: 200 # number of points per batch
      insert_rate: 5 # number of inserted batches per second per worker
  vars:

    orchestrator_ip: 192.168.115.206
    # orchestrator_ip: 10.100.100.22 #TODO should dinamically find host IP