---
- name: Prepare local Orchestrator image
  block:
    - name: Inspect orchestrator image
      community.docker.docker_image_info:
        name:
          - mulletbench-orchestrator:{{ benchmark_orchestrator_version }}
      register: orchestrator_image

    - name: Build local image
      community.docker.docker_image_build:
        name: mulletbench-orchestrator
        path: ../mulletbench
        tag: "{{ benchmark_orchestrator_version }}"
        dockerfile: orchestrator.dockerfile
      when: orchestrator_image.images | length == 0
  when: local


- name: Pull orchestrator image from Github
  community.docker.docker_image:
    name: ghcr.io/pedropereira98/mulletbench-orchestrator
    repository: mulletbench-orchestrator
    tag: "{{ benchmark_client_version }}"  # default = latest
    source: pull
    state: present
    debug: true
  when: not local

- name: Ensure /tmp/mulletbench-orch dir exists
  ansible.builtin.file:
    path: /tmp/mulletbench-orch
    state: directory
    mode: '1777'

- name: Copy compose file to remote
  ansible.builtin.template:
    src: templates/compose.yml.j2
    dest: /tmp/mulletbench-orch/compose.yml
    mode: '0500'

- name: Ensure /tmp/mulletbench-orch/config dir exists
  ansible.builtin.file:
    path: /tmp/mulletbench-orch/config
    state: directory
    mode: '1777'

- name: Copy config
  ansible.builtin.template:
    src: templates/config.yml.j2
    dest: /tmp/mulletbench-orch/config/config.yml
    mode: '0500'

- name: Ensure /tmp/mulletbench-orch/results dir exists
  ansible.builtin.file:
    path: /tmp/mulletbench-orch/results
    state: directory
    mode: '1777'

- name: Launch MulletBench Orchestrator instance
  community.docker.docker_compose_v2:
    project_src: /tmp/mulletbench-orch/
    project_name: mulletbench-orchestrator
    state: present
  register: output