# This file provides an example configuration for a mixed test with 4 edge servers and 1 cloud server.
all:
  vars:
    database: influx #influx or iotdb

    dataset: GPSMPU # Accel or GPSMPU
    current_time: true
    shared_dataset: true
    shared_connection: false
    
    influx_username: influx
    influx_password: influxpw
    influx_org: myorg
    influx_bucket: mybucket
    influx_token: mytoken
    influx_version: 2.7

    benchmark_client_version: v1.00
    benchmark_orchestrator_version: v1.00

    monitoring_interval: 2sec
    final_monitoring_period_sec: 120

    ansible_connection: ssh
    ansible_user: gsd

    home_dir: /home
    blkio_path: /dev/mapper/vg00-home #required for blkio_config (io or bps limiting)
edgeservers:
  hosts:
    edge1:
      ansible_host: 192.168.112.111
      ansible_connection: ssh
      ansible_user: gsd
      
      monitor: true
      
      limited_resources: true
      use_resource_profile: true
      limited_profile: rpi4

      replication_targets:
        - cloud1

    edge11:
      ansible_host: 192.168.112.111
      ansible_connection: ssh
      ansible_user: gsd
      
      monitor: true
      
      limited_resources: true
      use_resource_profile: true
      limited_profile: rpi4

      replication_targets:
        - cloud1
      influx_port: 8087
    edge2:
      ansible_host: 192.168.112.117
      ansible_connection: ssh
      ansible_user: gsd
      
      monitor: true

      limited_resources: true
      use_resource_profile: true
      limited_profile: rpi4

      replication_targets:
        - cloud1

    edge21:
      ansible_host: 192.168.112.117
      ansible_connection: ssh
      ansible_user: gsd
      
      monitor: true

      limited_resources: true
      use_resource_profile: true
      limited_profile: rpi4

      replication_targets:
        - cloud1
      influx_port: 8087
cloudservers:
  hosts:
    cloud1:
      ansible_host: 192.168.112.118

      limited_resources: false
      monitor: true
benchmark_clients:
  hosts:
  #Stage 1
    client1:
      stage: 1
      ansible_user: gsd
      ansible_host: 192.168.112.87
      monitor: true

      target: edge1

      data_file: dataset_gps_mpu_left.csv
      num_workers: 80
      type: INSERT

      insert_volume: 128000 # total number of inserted points per worker
      batch_size: 100 # number of points per batch
      insert_rate: 1 # number of inserted batches per second per worker

    client11:
      stage: 1
      ansible_user: gsd
      ansible_host: 192.168.112.87
      monitor: true

      target: edge11

      data_file: dataset_gps_mpu_left.csv
      num_workers: 80
      type: INSERT

      insert_volume: 128000 # total number of inserted points per worker
      batch_size: 100 # number of points per batch
      insert_rate: 1 # number of inserted batches per second per worker

    client2:
      stage: 1
      ansible_user: gsd
      ansible_host: 192.168.112.90
      monitor: true

      target: edge2

      data_file: dataset_gps_mpu_left.csv
      num_workers: 80
      type: INSERT

      insert_volume: 128000 # total number of inserted points per worker
      batch_size: 100 # number of points per batch
      insert_rate: 1 # number of inserted batches per second per worker

    client21:
      stage: 1
      ansible_user: gsd
      ansible_host: 192.168.112.90
      monitor: true

      target: edge21

      data_file: dataset_gps_mpu_left.csv
      num_workers: 80
      type: INSERT

      insert_volume: 128000 # total number of inserted points per worker
      batch_size: 100 # number of points per batch
      insert_rate: 1 # number of inserted batches per second per worker


  # Stage 2
    client3:
      stage: 2
      ansible_user: gsd
      ansible_host: 192.168.112.87
      monitor: true

      target: edge1

      data_file: dataset_gps_mpu_left.csv
      num_workers: 80
      type: INSERT

      insert_volume: 96000 # total number of inserted points per worker
      batch_size: 100 # number of points per batch
      insert_rate: 1 # number of inserted batches per second per worker

    client31:
      stage: 2
      ansible_user: gsd
      ansible_host: 192.168.112.87
      monitor: true

      target: edge11

      data_file: dataset_gps_mpu_left.csv
      num_workers: 80
      type: INSERT

      insert_volume: 96000 # total number of inserted points per worker
      batch_size: 100 # number of points per batch
      insert_rate: 1 # number of inserted batches per second per worker

    client4:
      stage: 2
      ansible_user: gsd
      ansible_host: 192.168.112.90
      monitor: true

      target: edge2

      data_file: dataset_gps_mpu_left.csv
      num_workers: 80
      type: INSERT

      insert_volume: 96000 # total number of inserted points per worker
      batch_size: 100 # number of points per batch
      insert_rate: 1 # number of inserted batches per second per worker

    client41:
      stage: 2
      ansible_user: gsd
      ansible_host: 192.168.112.90
      monitor: true

      target: edge21

      data_file: dataset_gps_mpu_left.csv
      num_workers: 80
      type: INSERT

      insert_volume: 96000 # total number of inserted points per worker
      batch_size: 100 # number of points per batch
      insert_rate: 1 # number of inserted batches per second per worker

    client51:
      stage: 2
      ansible_host: 192.168.112.93
      monitor: true

      target: edge1

      data_file: dataset_gps_mpu_left.csv
      num_workers: 1
      type: QUERY
      
      query_count: 240 # total number of queries submitted per worker
      query_rate: 0.25 # number of queries per second per worker
      agg_weight: 40 # weight of aggregation queries
      filter_weight: 0 # weight of filter queries
      downsample_weight: 20 # weight of downsample queries
      outlier_filter_weight: 40 # weight of outlier filter queries
      count_outlier_filter: false
      filter_z_score: 4.0

      fjp_parallelism: 3

    client52:
      stage: 2
      ansible_host: 192.168.112.93
      monitor: true

      target: edge11

      data_file: dataset_gps_mpu_left.csv
      num_workers: 1
      type: QUERY
      
      query_count: 240 # total number of queries submitted per worker
      query_rate: 0.25 # number of queries per second per worker
      agg_weight: 40 # weight of aggregation queries
      filter_weight: 0 # weight of filter queries
      downsample_weight: 20 # weight of downsample queries
      outlier_filter_weight: 40 # weight of outlier filter queries
      count_outlier_filter: false
      filter_z_score: 4.0

      fjp_parallelism: 3

    client53:
      stage: 2
      ansible_host: 192.168.112.93
      monitor: true

      target: edge2

      data_file: dataset_gps_mpu_left.csv
      num_workers: 1
      type: QUERY
      
      query_count: 240 # total number of queries submitted per worker
      query_rate: 0.25 # number of queries per second per worker
      agg_weight: 40 # weight of aggregation queries
      filter_weight: 0 # weight of filter queries
      downsample_weight: 20 # weight of downsample queries
      outlier_filter_weight: 40 # weight of outlier filter queries
      count_outlier_filter: false
      filter_z_score: 4.0

      fjp_parallelism: 3

    client54:
      stage: 2
      ansible_host: 192.168.112.93
      monitor: true

      target: edge21

      data_file: dataset_gps_mpu_left.csv
      num_workers: 1
      type: QUERY
      
      query_count: 240 # total number of queries submitted per worker
      query_rate: 0.25 # number of queries per second per worker
      agg_weight: 40 # weight of aggregation queries
      filter_weight: 0 # weight of filter queries
      downsample_weight: 20 # weight of downsample queries
      outlier_filter_weight: 40 # weight of outlier filter queries
      count_outlier_filter: false
      filter_z_score: 4.0

      fjp_parallelism: 3

    client6:
      stage: 2
      ansible_host: 192.168.112.95
      monitor: true

      target: cloud1

      data_file: dataset_gps_mpu_left.csv
      num_workers: 1
      type: QUERY
      
      query_count: 240 # total number of queries submitted per worker
      query_rate: 0.25 # number of queries per second per worker
      agg_weight: 40 # weight of aggregation queries
      filter_weight: 0 # weight of filter queries
      downsample_weight: 20 # weight of downsample queries
      outlier_filter_weight: 40 # weight of outlier filter queries
      count_outlier_filter: false
      filter_z_score: 4.0

      fjp_parallelism: 3
  vars:
    max_memory: 4G # max heap memory for the JVM for each client instance
    fjp_parallelism: 40
    orchestrator_ip: 192.168.112.100
    read_timeout: 60