- name: Check tmp influxdb directory
  ansible.builtin.stat:
    path: /tmp/influxdb
  register: dir

- name: Check InfluxDB instance directory
  ansible.builtin.stat:
    path: /tmp/influxdb/{{ inventory_hostname }}
  register: instance_dir
  when: dir.stat.isdir is defined and dir.stat.isdir

- name: Shutdown InfluxDB instance
  community.docker.docker_compose:
    project_src: /tmp/influxdb/{{ inventory_hostname }}
    state: absent
  when: dir.stat.isdir is defined and dir.stat.isdir and instance_dir.stat.isdir is defined and instance_dir.stat.isdir and not 'hard-reset' in ansible_run_tags

- name: Shutdown InfluxDB instance and remove volumes
  community.docker.docker_compose:
    project_src: /tmp/influxdb/{{ inventory_hostname }}
    remove_volumes: true
    state: absent
  when: dir.stat.isdir is defined and dir.stat.isdir and instance_dir.stat.isdir is defined and instance_dir.stat.isdir and 'hard-reset' in ansible_run_tags # only run this task if the hard_reset tag is explicitely set

- name: Remove InfluxDB data folder
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ home_dir }}/influxdb/{{ inventory_hostname }}"
  tags: ['hard-reset']
  when: "'hard-reset' in ansible_run_tags" # only run this task if the hard_reset tag is explicitely set
