---

- name: Install pcp for monitoring
  ansible.builtin.apt:
    name:
      - pcp
  become: true
  throttle: 1
  when: monitor

- name: Enable and start pmcd and pmlogger services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: restarted
  with_items:
    - pmcd
    - pmlogger
  when: monitor

- name: Disable and stop pmcd and pmlogger services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - pmcd
    - pmlogger
  when: not monitor

- name: Run database instalation
  ansible.builtin.include_tasks: "{{ database }}-main.yaml"

- name: Save container ID and cgroups version when monitoring is enabled
  block:
  - name: Get container ID
    become: true
    shell: docker container ls --all --quiet --no-trunc --filter "name=^{{ database }}-{{ inventory_hostname }}$"
    register: container_id_result
    changed_when: false

  - name: Set container ID fact
    ansible.builtin.set_fact:
      container_id: "{{ container_id_result.stdout }}"

  - name: Get cgroup version
    ansible.builtin.shell: '[ -f /sys/fs/cgroup/cgroup.controllers ] && echo "v2" || echo "v1"'
    register: cgroup_version
    changed_when: false

  - name: Set cgroups version fact
    ansible.builtin.set_fact:
      cgroups_version: "{{ cgroup_version.stdout }}"
  when: monitor

- name: Set network simulation
  ansible.builtin.include_tasks:
    "network-sim.yaml"
  when: network_sim is defined