dataFile: "data_1600_accel_watch.txt"
#dataFile: "ethylene_CO_head_400k.txt"
target: "influx"
numWorkers: 1
type: QUERY #INSERT or QUERY
insertion:
  workerSectionSize: 32000
  batchSize: 100
  rate: 32 #batches per second
query:
  count: 100 #total queries submitted per worker
  rate: 10 #queries per second
  aggChance: 33
  filterChance: 33
  downsampleChance: 33
influx:
  serverURL: "http://192.168.112.45:8086"
  token: "mytoken"
  orgID: "88adb63743172fae"
  bucket: "mybucket"
  blocking: true
  bufferSize: 40000
iotdb:
  host: "192.168.112.45"
  port: "6667"
  username: "root"
  password: "root"
  devicePath: "root.watch.accel.d1"